import Head from "next/head";
import React from 'react';
import Sidebar from "../features/sidebar";

const AdminLayout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Page Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <Sidebar />
                {children}
            </>
        </>
    );
};

export default AdminLayout;