import React from 'react';
import Head from 'next/head';

const ProductsLayout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Page Products</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </>
    );
};
export default ProductsLayout;